name   =  input("Enter your name           :    ")
adj    =  input("Enter your adjective here :    ")
hobby  =  input("Enter your hobby here     :    ")
course =  input("Enter your course here    :    ")
place  =  input("Enter your place here     :    ")
print("\n Here is your INTRODUCTION ")
print(f"Hi! My name is {name}   . I am a very {adj} person.")
print(f"I am a {course}, and in my free time, I love {hobby} .")
print(f"I also enjoy spending time at the {place}")
print("Nice to meet you !!!!")